POST http://localhost:8080/events
content-type: application/json
Authorization: {auth_token}

{
  "name": "Event By Simran",
  "description": "Simran's event",
  "location": "Chandigarh",
  "dateTime": "2025-06-01T10:00:00Z"
}
